### ISSUE TITLE
Unable to pass subclassed lightbulb app to ClusterLauncher.

### ISSUE THREAD

**Issue by jaymart95** [CircuitSacul/hikari-clusters#71]
I have subclassed my bot and when I run it, the ClusterLauncher just spazzes out because it says it's not callable. 

```py
Process Process-14:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/hikari_clusters/cluster.py", line 153, in launch_cluster
    self.bot_class(**self.bot_init_kwargs),
TypeError: 'VanityRolesBot' object is not callable
```

```py
bot = VanityRolesBot()

def main():
    try:
        bot._load_extensions("vanityroles.exts")
        tasks.load(bot)
        bot.miru_client = miru.Client(bot, ignore_unknown_interactions=True)
        #bot.run()
        Server(
            host="192.168.1.11",
            port = 8765,
            token="monster95",
            cluster_launcher=ClusterLauncher(bot)
        ).run()
```

**Comment by CircuitSacul** [comment]
You're supposed to pass the class, not an instance of it. ```py
Server(..., cluster_launcher=ClusterLauncher(VanityRolesBot))
```
